### PR TITLE
[WebComponents]Updated colour theme

### PR DESCRIPTION
**Pull request by ayinloya**
This change makes use of the colour theme provided in the web embed to change the colour or buttons and headers texts.

# Testing
Update the `theme_color` to the preferred colour in the example app
Run the example app and confirm the colour is applied

Screenshot 2024-08-12 at 4 32 36 PM

### CODE REVIEW

**Review by solnsubuga — COMMENTED** [review]
I have sent the theme_colour in scripts.js to a prefered color but the app buttons and theming was blue.

What is expected to change in this case? Can we also add some UI images to the PR?

**Comment by ayinloya** [comment]
> I have sent the theme_colour in scripts.js to a prefered color but the app buttons and theming was blue.
> 
> What is expected to change in this case? Can we also add some UI images to the PR?

`theme_colour` should be part of the `partner_details`

**Review by beaglebets — APPROVED** [review]
I think this is a great improvement. I would be much happier if I were re-approving this after tests were updated to show that we pass the theme color in.

**Comment by ayinloya** [comment]
> I think this is a great improvement. I would be much happier if I were re-approving this after tests were updated to show that we pass the theme color in.

Added test for color

**Review by beaglebets — APPROVED** [review]

**Pull request merged**
