### PR TITLE
Add hide_attribution config

### PR DESCRIPTION
**Pull request by ayinloya**
We can now hide attribution by using `hide_attribution` in the config.

- Add `hide_attribution: true` to the config in the example script
- Run the example app
- Verify that the attributions are hidden on all screen for each product
- Run without setting `hide_attribution` and confirm the attributions are visible

### CODE REVIEW

**Review by beaglebets — COMMENTED** [review]
Am I correct in reading this as defaulting to hidden?

**Comment by ayinloya** [comment]
> Am I correct in reading this as defaulting to hidden?

Yes, there’s a flicker when the default is show and then we try to hid it

**Comment by beaglebets** [comment]
so how does that get rendered? Would a partner have to explicitly enable it? Who would do that?

**Comment by ayinloya** [comment]
> so how does that get rendered? Would a partner have to explicitly enable it? Who would do that?

We first check to see if there partner has set a config to hide the attribution if set it’ll remain hidden else it’ll show 
we are only defaulting to hidden on the loading screen

**Review by beaglebets — APPROVED** [review]
I would prefer if the default were true, but I trust you ran this by product first.

**Pull request merged**
